fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    options: { i18n: false }

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     options: { i18n: false }

web_sitemap:
    path:  /sitemap.{_format}
    defaults: { _controller: WixetBlogBundle:Sitemap:sitemap, _format: xml }

web_robots:
    path:  /robots.{_format}
    defaults: { _controller: WixetBlogBundle:Sitemap:robots, _format: txt }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

wixet_blog:
    resource: "@WixetBlogBundle/Controller/"
    type:     annotation
    prefix:   /
