services:
  my.oauth_aware.user_provider.service:
      class: Wixet\BlogBundle\Security\Core\User\MyFOSUBUserProvider
      arguments: ['@fos_user.user_manager', { google: google_id, facebook: facebook_id }]