<?php

namespace Wixet\BlogBundle\Repository;

/**
 * BlogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogEntryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMostRecent($locale, $total = null){
        $query = $this->recentQuery($locale);
        if($total != null) {
            return $query->setMaxResults($total);
        }
        return $query->getResult();
    }

    public function recentQuery($locale) {
        return $this->getEntityManager()->createQuery(
            "SELECT e FROM WixetBlogBundle:BlogEntry e JOIN e.locale l WHERE e.public = true AND l.locale LIKE :locale ORDER BY e.createdAt DESC"
        )->setParameter("locale", $locale."%");
    }
}
