<?php

namespace Wixet\BlogBundle\Repository;

/**
 * BlogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogEntryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMostRecent($locale, $category=null, $tag=null, $total=null){
        $query = $this->findMostRecentQuery($locale, $category, $tag);
        if($total != null) {
            $query->setMaxResults($total);
        }
        return $query->getResult();
    }

    // This method will be used by the paginator
    public function findMostRecentQuery($locale, $category=null, $tag=null){
        // Generic query
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select("e")
            ->from("WixetBlogBundle:BlogEntry", "e")
            ->join("e.locale", "l")
            ->where("e.public = true")
            ->andWhere("l.locale LIKE :locale")
            ->orderBy("e.createdAt", "DESC")
            ->setParameter("locale", $locale."%")
        ;

        // Filters
        if($category != null) {
            $qb
                ->join("e.category", "c")
                ->andWhere("c = :category")
                ->setParameter("category", $category)
            ;
        }

        if($tag != null) {
            $qb
                ->join("e.tags", "t")
                ->andWhere("t = :tag")
                ->setParameter("tag", $tag)
            ;
        }

        return $qb->getQuery();
    }

}
